grpc:
  server:
    port: 59091
    reflection-service-enabled: true

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration


logging:
  level:
    #    io.grpc: DEBUG
    #    net.devh.boot.grpc: DEBUG
    ru:
      yandex:
        practicum:
          telemetry:
            aggregator:
              DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID_AGGREGATOR}
    auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
    key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER}
    value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER_SENSOR}

  producer:
    key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER}
    value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER}
