server:
  port: 0

spring:
  application:
    name: shopping-store
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    ru.yandex.practicum: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"